git:
    depth: 1

cache:
    directories:
        - $HOME/.composer/cache

sudo: false

language: php

matrix:
    include:
        - php: '7.1.3'
        - php: '7.2.3'
        - php: 'nightly'
          env:
              - COMPOSER_FLAGS='--ignore-platform-reqs'
              - SKIP_PHP_CS_FIXER='yes'

before_install:
    - composer self-update

install:
    - composer update $COMPOSER_FLAGS

script:
    - vendor/bin/phpcs --report-full --standard=PSR2 src tests
    - if [ ! $SKIP_PHP_CS_FIXER ]; then vendor/bin/php-cs-fixer fix --config=tests/php-cs-fixer.config.php --dry-run --diff src tests; fi
    - vendor/bin/phpstan analyse --level=4 src -c tests/phpstan.neon
    - vendor/bin/phpcpd src tests
    - phpdbg -qrr vendor/bin/phpunit -c tests/phpunit.xml